[package]
name = "sn_viewmodel_cedeclara"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm-bindgen = {version ="0.2.104", features = ["serde-serialize"]}
web-sys = { version = "0.3.81", features = [
    "Window", 
    "Document", 
    "Element",
    "console"
    ]}

serde = {version = "1.0.228", features = ["derive"]}
serde-wasm-bindgen = {version = "0.6.5"}

[lib]
crate-type = ["cdylib", "rlib"]