[package]
name = "sn_viewmodel_cedeclara"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm-bindgen = "0.2.104"
web-sys = { version = "0.3.81", features = [
    "Window", 
    "Document", 
    "Element"
    ]}